# Generated by Django 6.0.1 on 2026-01-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.TextField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft'),
        ),
    ]
